name: viash test CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  viash-test:
    runs-on: ${{ matrix.config.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: false
      matrix:
        config:
        - {name: 'main', os: ubuntu-latest }

    steps:
    - uses: actions/checkout@v2

    - name: Fetch viash
      run: |
        bin/init
        bin/viash -h

    - name: Run build
      run: |
        bin/viash_build

    - name: Run tests
      run: |
        # create check_results folder
        sed -i '/^check_results\/$/d' .gitignore
        mkdir check_results

        # run tests
        bin/viash_test --append=false --log=check_results/results.tsv

    - name: Run pipeline
      run: |
        workflows/civ6_pipeline/run.sh
        # remove output files
        find work -name "*.pdf" -o -name "*.png" -o -name "*.webm" -type f -delete
        # move nextflow logs to check results
        mv work check_results/nextflow_work

    - name: Upload check results
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.config.name }}_results
        path: check_results

